---
driver:
  name: ec2
  region: us-west-2
  aws_ssh_key_id: shared-bootstrap
  instance_type: t2.micro
  subnet_id: subnet-3050df55 # an arbitrary staging service subnet

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  environments_path: test/environments
  solo_rb:
    environment: aws-us-west-2-staging

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-c8d137a8
  - name: ubuntu-14.04-chef-11
    driver_config:
      image_id: ami-c8d137a8
    provisioner:
      require_chef_omnibus: 11.16.4

suites:
  - name: default
    run_list:
      - role[test_bucky_role]
      - recipe[bucky]
    roles_path: test/roles
    driver:
      tags:
        Name: test-kitchen-bucky
    attributes:
      graphite-url: graphite.aws-us-west-2-staging.socrata.net
      graphite-port: 2003
      collectd_enabled: false