---
driver:
  name: docker

driver_plugin: docker
driver_config:
  require_chef_omnibus: true
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: socrata/runit
      platform: ubuntu
  - name: ubuntu-14.04-chef-11
    driver_config:
      image: socrata/runit
      platform: ubuntu
    provisioner:
      require_chef_omnibus: 11.16.4

suites:
  - name: default
    run_list:
      - role[test_bucky_role]
      - recipe[bucky]
    roles_path: test/roles
